export const calcButtons = [
  { button: "C", className: "operation1", buttonType: "oper" },
  { button: "+/-", className: "operation1", buttonType: "oper" },
  { button: "%", className: "operation1", buttonType: "oper" },
  { button: "/", className: "operation", buttonType: "oper" },
  { button: 7, className: "number", buttonType: "num" },
  { button: 8, className: "number", buttonType: "num" },
  { button: 9, className: "number", buttonType: "num" },
  { button: "x", className: "operation", buttonType: "oper" },
  { button: 4, className: "number", buttonType: "num" },
  { button: 5, className: "number", buttonType: "num" },
  { button: 6, className: "number", buttonType: "num" },
  { button: "-", className: "operation", buttonType: "oper" },
  { button: 1, className: "number", buttonType: "num" },
  { button: 2, className: "number", buttonType: "num" },
  { button: 3, className: "number", buttonType: "num" },
  { button: "+", className: "operation", buttonType: "oper" },
  { button: 0, className: "number0", buttonType: "num" },
  { button: ".", className: "number", buttonType: "oper" },
  { button: "=", className: "operation2", buttonType: "oper" },
];
